/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finproj;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.Statement;
/**
 *
 * @author Shashwat Sharma
 */
public class contacts extends javax.swing.JFrame {
String oname,onum;
Connection con;
Statement stmt;
DefaultTableModel tab;
    /**
     * Creates new form contacts
     */
    public contacts() {
        initComponents();
       tab=(DefaultTableModel) tbmain.getModel();
        try{
        Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/mobile_ui","root","1234");
        stmt=con.createStatement();
        int rowcnt=tab.getRowCount();
        for(int i=0;i<rowcnt;i++){
            tab.removeRow(0);
        }
        ResultSet cc= stmt.executeQuery("Select * from contacts;");
        while(cc.next()){
            tab.addRow(new Object[]{cc.getString(1)});
        }
        cc.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmain = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        btEdit = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btAdd = new javax.swing.JButton();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        tbmain.setBackground(new java.awt.Color(0, 0, 255));
        tbmain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbmain.setGridColor(new java.awt.Color(102, 102, 255));
        tbmain.setOpaque(false);
        tbmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmain);
        if (tbmain.getColumnModel().getColumnCount() > 0) {
            tbmain.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        lbl1.setBackground(new java.awt.Color(0, 0, 102));
        lbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("CONTACTS");
        lbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl1.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtName.setEditable(false);

        txtNum.setEditable(false);

        btEdit.setText("Edit");
        btEdit.setEnabled(false);
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDel.setText("Delete");
        btDel.setEnabled(false);
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        btAdd.setBackground(new java.awt.Color(255, 255, 255));
        btAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAdd.setText("New");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/BACK.png"))); // NOI18N
        btBack.setBorderPainted(false);
        btBack.setContentAreaFilled(false);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btDel))
                            .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBack)
                    .addGap(0, 294, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(296, Short.MAX_VALUE)
                    .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbmainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmainMouseClicked
        // TODO add your handling code here:
        String rname= (String)(tab.getValueAt(tbmain.getSelectedRow(),tbmain.getSelectedColumn()));
        btEdit.setEnabled(true);
        txtName.setText(rname);
        btDel.setEnabled(true);
        lbl1.setText("Contact Info");
        try{
        ResultSet cd= stmt.executeQuery("Select * from contacts where name = \""+rname+"\" ;");
        while(cd.next()){
            txtNum.setText(cd.getString(2));
        }
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
        
    }//GEN-LAST:event_tbmainMouseClicked

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
        String upd;
        
        if(btEdit.getText().equals("Update")){
           if(txtName.getText().isEmpty()||txtNum.getText().isEmpty()){
               JOptionPane.showMessageDialog(this,"Please fill all the fields");
           }
           else{
               //upd="/'"+txtName.getText()+"/'"+","+"/'"+txtNum.getText()+"/'"+");";
               upd="name= " + "\'"+txtName.getText()+"\'" + "," + "Number= " + "\'"+txtNum.getText()+"\'" + " where name= "+"\'"+oname+"\';";
               tbmain.setEnabled(true);
               btAdd.setEnabled(true);
               btEdit.setText("Edit");
               btDel.setText("Delete");
               txtName.setEditable(false);
               txtNum.setEditable(false);
               lbl1.setText("Contact Info");
               try{
               stmt.executeUpdate("update contacts set "+upd);
                   int rowcnt = tab.getRowCount();
                   for (int i = 0; i < rowcnt; i++) {
                       tab.removeRow(0);
                   }
               ResultSet cc= stmt.executeQuery("Select * from contacts;");
                while(cc.next()){
                    tab.addRow(new Object[]{cc.getString(1)});
                }
                cc.close();
               }
              catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
               }
               
           }
        }
        else if(btEdit.getText().equals("Edit")){
        
        oname=txtName.getText();
        onum=txtNum.getText();
        tbmain.setEnabled(false);
        btEdit.setText("Update");
        btDel.setText("Cancel");
        btAdd.setEnabled(false);
        txtName.setEditable(true);
        txtNum.setEditable(true);
        lbl1.setText("Editing");
        }
        
    }//GEN-LAST:event_btEditActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        // TODO add your handling code here:
        
        
        if(btDel.getText().equals("Delete")){
            try{
                oname=txtName.getText();
              stmt.executeUpdate("delete from contacts where name="+"\'"+oname+"\';");
              int rowcnt = tab.getRowCount();
                   for (int i = 0; i < rowcnt; i++) {
                       tab.removeRow(0);
                   }
               ResultSet cc= stmt.executeQuery("Select * from contacts;");
                while(cc.next()){
                    tab.addRow(new Object[]{cc.getString(1)});
                }
                cc.close();
              txtName.setText("");
              txtNum.setText("");
              btEdit.setEnabled(false);
              btAdd.setText("New");
              lbl1.setText("Contacts");
               }
            catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
               }
        }
        else if(btDel.getText().equals("Cancel")){
            txtName.setText(oname);
            txtNum.setText(onum);
            tbmain.setEnabled(true);
            btAdd.setEnabled(true);
               btEdit.setText("Edit");
               btDel.setText("Delete");
               btAdd.setText("New");
               txtName.setEditable(false);
               txtNum.setEditable(false);
               lbl1.setText("Contact Info");
        }
    }//GEN-LAST:event_btDelActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        txtName.setEditable(true);
            txtNum.setEditable(true);
        if(btAdd.getText().equals("Add")){
            if(txtName.getText().isEmpty()||txtNum.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill all the fields");
            }
            else{
                btAdd.setText("New");
                btDel.setText("Delete");
                btEdit.setEnabled(true);
            tbmain.setEnabled(true);
            txtName.setEditable(false);
            txtNum.setEditable(false);
            lbl1.setText("Contact Info");
               try{
               stmt.executeUpdate("insert into contacts values( "+"\'"+txtName.getText()+"\'"+","+"\'"+txtNum.getText()+"\'"+");");
               int rowcnt = tab.getRowCount();
                   for (int i = 0; i < rowcnt; i++) {
                       tab.removeRow(0);
                   }
               ResultSet cc= stmt.executeQuery("Select * from contacts;");
                while(cc.next()){
                    tab.addRow(new Object[]{cc.getString(1)});
                }
                cc.close();
               }
              catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
               }
            }
        }
        else if(btAdd.getText().equals("New")){
            btEdit.setEnabled(false);
            tbmain.setEnabled(false);
            txtName.setEditable(true);
            txtNum.setEditable(true);
            btAdd.setText("Add");
            btDel.setText("Cancel");
            oname=txtName.getText();
            onum=txtNum.getText();
            txtName.setText("");
            txtNum.setText("");
            lbl1.setText("Add a new Contact");
        }
        
    }//GEN-LAST:event_btAddActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTable tbmain;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
